@startuml
start
if (Papierticket?) then (Ja)
  :Papierticket;
  note left
    use case 1
  end note
  :Anfrage Zugservices
  - von, bis, Zeit angeben;
  :Zugservice wählen;
else (Nein)
  :Digitales Ticket;
  if (Digitales Sparticket?) then (Nein)
     :Digitales Ticket
     - streckengebunden;
     note left
       use case 1,2,3
     end note
     :Anfrage Zugservices
     - Zeit angeben;
     :Zugservice wählen;
   else (Ja)
     :Digitales Sparticket
     - zugservicegebunden;
     note right
        use case 1,2,3
     end note
   endif
endif
   :Wagen wählen;
repeat
    :Sitzplatz wählen;
    note left
        use case 4
    end note
repeat while (Sitzplatz reserviert?)
:Reservationsbestätigung \nerhalten;
stop
@enduml