@startuml
start
if (Papierticket?) then (Ja)
  :Papierticket;
  note left
    use case 1,2,4
  end note
  :Anfrage Zugservices
  - von, bis, Zeit wählen;
  :Zugservice wählen;
else (Nein)
  :Digitales Ticket;
  if (Digitales Sparticket?) then (Nein)
     :Digitales Ticket
     - streckengebunden;
     note left
       use case 1,2,3,4
     end note
     :Anfrage Zugservices
     - für vorgegebene Strecke
     - Zeit wählen;
     :Zugservice wählen;
   else (Ja)
     :Digitales Sparticket
     - zugservicegebunden;
     note right
        use case 1,2,3,4
     end note
   endif
endif
repeat
    :Sitzplatz wählen;
    note left
        use case 5
    end note
repeat while (Sitzplatz reserviert?)
:Reservationsbestätigung \nerhalten;
stop
@enduml