@startuml

node "Server (Apache Tomcat)"{
    node "Magnolia CMS" as mag{
        [Backend]
        [REST API] as rApi
    }
    database "JCR"
}
node "Browser"{

    node "vue.js" as vue{
        [Javascript Framework]
    }
}

rApi -right-> vue : JSON
vue -left-> rApi : REST
vue ---- rApi
mag -> JCR


@enduml